backend:
  name: git-gateway
  repo: KorlaMarch/korlamarch-com
  branch: master
  site_domain: korlamarch.netlify.app
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "work"
    label: "Work"
    folder: "src/pages/works"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "work-item"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Start Date"
        name: "startdate"
        widget: "datetime"
        dateFormat: "MM.YYYY"
        timeFormat: false
      - label: "End Date"
        name: "enddate"
        widget: "datetime"
        default: ""
        dateFormat: "MM.YYYY"
        timeFormat: false    
        required: false
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Featured", name: "featured", widget: "boolean"}
      - label: "Images"
        name: "images"
        widget: "list"
        field: {label: Image, name: image, widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Main Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: "Intro Text", name: introText, widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Proflie Picture", name: image, widget: image, required: false}
          - {label: "Body", name: "body", widget: "markdown"}